--
-- File generated with SQLiteStudio v3.4.1 on Mon Dec 26 18:39:18 2022
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: ATTENDEE
CREATE TABLE IF NOT EXISTS ATTENDEE (
    ATTENDEE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    PHONE INTEGER,
    EMAIL VARCHAR(30),
    VIP BOOLEAN DEFAULT(0));

-- Table: COMPANY
CREATE TABLE IF NOT EXISTS COMPANY(
    COMPANY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(60),
    PRIMARY_CONTACT_ATTENDEE_ID INTEGER NOT NULL);

-- Table: PRESENTATION
CREATE TABLE IF NOT EXISTS PRESENTATION (
    PRESENTATION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BOOKED_COMPANY_ID INTEGER NOT NULL,
    BOOKED_ROOM_ID INTEGER NOT NULL,
    START_TIME TIME,
    END_TIME TIME);

-- Table: PRESENTATION_ATTENDANCE
CREATE TABLE IF NOT EXISTS PRESENTATION_ATTENDANCE (
    TICKET_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRESENTATION_ID INTEGER,
    ATTENDEE_ID INTEGER);

-- Table: ROOM
CREATE TABLE IF NOT EXISTS ROOM (
    ROOM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FLOOR_NUMBER INTEGER NOT NULL,
    SEAT_CAPACITY INTEGER NOT NULL);

-- View: PRESENTATION_VW
CREATE VIEW IF NOT EXISTS PRESENTATION_VW AS SELECT 
    COMPANY.NAME AS BOOKED_COMPANY,
    ROOM.ROOM_ID AS ROOM_NUMBER,
    ROOM.FLOOR_NUMBER AS FLOOR,
    ROOM.SEAT_CAPACITY AS SEATS,
    START_TIME,
    END_TIME
FROM PRESENTATION
INNER JOIN COMPANY ON COMPANY.COMPANY_ID = PRESENTATION.BOOKED_COMPANY_ID
INNER JOIN ROOM ON ROOM.ROOM_ID = PRESENTATION.BOOKED_ROOM_ID;

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
