CREATE TABLE IF NOT EXISTS CUSTOMER (CUSTOMER_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, NAME TEXT NOT NULL, REGION TEXT, STREET_ADDRESS TEXT, CITY TEXT, STATE TEXT, ZIP INTEGER);
INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP) VALUES (1, 'LITE Industrial', 'Southwest', '729 Ravine Way', 'Irving', 'TX', 75014);
INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP) VALUES (2, 'Rex Tooling Inc', 'Southwest', '6129 Collie Blvd', 'Dallas', 'TX', 75201);
INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP) VALUES (3, 'Re-Barre Construction', 'Southwest', '9043 Windy Dr', 'Irving', 'TX', 75032);
INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP) VALUES (4, 'Prairie Construction', 'Southwest', '264 Long Rd', 'Moore', 'OK', 62104);
INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, REGION, STREET_ADDRESS, CITY, STATE, ZIP) VALUES (5, 'Marsh Lane Metal Works', 'Southeast', '9143 Marsh Ln', 'Avondle', 'LA', 79782);
